# Generated by Django 3.2.3 on 2021-06-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pv',
            name='présents',
            field=models.ManyToManyField(to='PV.Acteur'),
        ),
    ]
