# Generated by Django 3.2.4 on 2021-06-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0002_auto_20210607_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pv',
            options={'verbose_name': 'PV', 'verbose_name_plural': 'PVs'},
        ),
        migrations.RenameField(
            model_name='pv',
            old_name='présents',
            new_name='presents',
        ),
    ]
