# Generated by Django 3.2.4 on 2021-06-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0003_auto_20210608_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='pv',
            name='Decisions',
            field=models.TextField(blank=True, null=True, verbose_name='Décisions finales'),
        ),
        migrations.AddField(
            model_name='pv',
            name='pointAborde',
            field=models.TextField(blank=True, null=True, verbose_name='Points abordées'),
        ),
        migrations.AlterField(
            model_name='pv',
            name='ordreDuJour',
            field=models.TextField(verbose_name='Ordre du jour'),
        ),
    ]
