# Generated by Django 3.2.4 on 2021-06-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PV', '0004_auto_20210613_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteur',
            name='mission',
            field=models.CharField(default='membre', max_length=200),
            preserve_default=False,
        ),
    ]
